#!/usr/bin/env bash
#
# Copy the freshly-built Anchor IDL + generated TS types into the sibling
# `../adler-website` repo so the web client gets typed bindings without manual
# IDL plumbing.
#
# Re-run after every `anchor build` (every program redeploy).

set -euo pipefail

cd "$(dirname "$0")/.."

WEBSITE_REPO="../adler-website"
IDL_SRC="target/idl/adler_escrow.json"
TYPES_SRC="target/types/adler_escrow.ts"
ANCHOR_DIR="$WEBSITE_REPO/lib/anchor"
IDL_DEST="$ANCHOR_DIR/idl.ts"
TYPES_DEST="$ANCHOR_DIR/idl-types.ts"

if [[ ! -d "$WEBSITE_REPO" ]]; then
    echo "ERROR: $WEBSITE_REPO not found relative to $(pwd)" >&2
    exit 1
fi

if [[ ! -f "$IDL_SRC" ]]; then
    echo "ERROR: $IDL_SRC missing — run anchor build first" >&2
    exit 1
fi

mkdir -p "$ANCHOR_DIR"

echo "→ $TYPES_DEST"
cp "$TYPES_SRC" "$TYPES_DEST"

echo "→ $IDL_DEST"
{
    echo '// Auto-generated by adler-program/scripts/sync-idl.sh — do not edit.'
    echo '// Source of truth: adler-program/target/idl/adler_escrow.json.'
    echo
    echo 'import type { AdlerEscrow } from "./idl-types";'
    echo
    echo 'const idl: AdlerEscrow ='
    cat "$IDL_SRC"
    echo ';'
    echo
    echo 'export default idl;'
} > "$IDL_DEST"

echo
echo "→ Done. Web client can now: import idl from \"@/lib/anchor/idl\""
