#!/usr/bin/env bash
#
# Copy the freshly-built Anchor IDL + generated TS types into the sibling
# consumer repos so they get typed bindings without manual IDL plumbing.
#
# Targets:
#   ../adler-website        — web client (Next.js)
#   ../adler-app            — mobile client (Expo) and Cloud Functions
#
# Re-run after every `anchor build` (every program redeploy).

set -euo pipefail

cd "$(dirname "$0")/.."

IDL_SRC="target/idl/adler_escrow.json"
TYPES_SRC="target/types/adler_escrow.ts"

if [[ ! -f "$IDL_SRC" ]]; then
    echo "ERROR: $IDL_SRC missing — run anchor build first" >&2
    exit 1
fi

# --- Web (adler-website) -----------------------------------------------------
WEBSITE_REPO="../adler-website"
if [[ -d "$WEBSITE_REPO" ]]; then
    WEB_DIR="$WEBSITE_REPO/lib/anchor"
    mkdir -p "$WEB_DIR"

    echo "→ $WEB_DIR/idl-types.ts"
    cp "$TYPES_SRC" "$WEB_DIR/idl-types.ts"

    echo "→ $WEB_DIR/idl.ts"
    {
        echo '// Auto-generated by adler-program/scripts/sync-idl.sh — do not edit.'
        echo '// Source of truth: adler-program/target/idl/adler_escrow.json.'
        echo
        echo 'import type { AdlerEscrow } from "./idl-types";'
        echo
        echo 'const idl: AdlerEscrow ='
        cat "$IDL_SRC"
        echo ';'
        echo
        echo 'export default idl;'
    } > "$WEB_DIR/idl.ts"
else
    echo "SKIP: $WEBSITE_REPO not found"
fi

# --- Mobile + Cloud Functions (adler-app) -----------------------------------
APP_REPO="../adler-app"
if [[ -d "$APP_REPO" ]]; then
    APP_DIR="$APP_REPO/lib/anchor"
    FUNCTIONS_IDL="$APP_REPO/functions/idl.json"
    mkdir -p "$APP_DIR"

    echo "→ $APP_DIR/idl-types.ts"
    cp "$TYPES_SRC" "$APP_DIR/idl-types.ts"

    echo "→ $APP_DIR/idl.ts"
    {
        echo '// Auto-generated by adler-program/scripts/sync-idl.sh — do not edit.'
        echo '// Source of truth: adler-program/target/idl/adler_escrow.json.'
        echo
        echo 'import type { AdlerEscrow } from "./idl-types";'
        echo
        echo '// Anchor 0.31 keeps Rust snake_case in the IDL JSON; idl-types.ts has'
        echo '// camelCase. Cast through unknown to keep the typed client surface clean.'
        echo 'const idlRaw ='
        cat "$IDL_SRC"
        echo ';'
        echo
        echo 'const idl = idlRaw as unknown as AdlerEscrow;'
        echo 'export default idl;'
    } > "$APP_DIR/idl.ts"

    echo "→ $FUNCTIONS_IDL"
    cp "$IDL_SRC" "$FUNCTIONS_IDL"
else
    echo "SKIP: $APP_REPO not found"
fi

echo
echo "→ Done."
